/**
 * Mock implementation of the MCP content pipeline.
 *
 * Produces a deterministic ArmorCourse bundle from a topic and track,
 * without calling any MCP server. Used by:
 *   - the CLI (`scripts/armor/generate-course.ts`) without --live
 *   - the admin uploader running in dev / preview without MCP keys
 *   - CI smoke tests that verify the schema + writer end-to-end
 *
 * The output is intentionally generic but **schema-valid**: it must
 * pass `ArmorCourseSchema.safeParse` and `validate-armor-content.ts`.
 *
 * The function is an async generator that yields `PipelineEvent`s and
 * returns a `GenerateCourseOutput`. The shape mirrors what the live
 * implementation will emit so consumers (CLI + SSE endpoint) stay
 * unchanged when the live pipeline lands.
 */

import type {
  GenerateCourseInput,
  GenerateCourseOutput,
  GeneratedLab,
  GeneratedLesson,
  GeneratedQuiz,
  PipelineEvent,
} from '../mcp-pipeline';
import { PIPELINE_DEFAULTS, deriveSlug } from '../mcp-pipeline';
import { renderCourseYaml, renderQuizYaml, renderLabYaml } from './yaml-render';

// ──────────────────────────────────────────────────────────────────────
// Helpers — all pure, all deterministic.
// ──────────────────────────────────────────────────────────────────────

function titleCase(s: string): string {
  return s
    .split(/\s+/)
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');
}

type LabRuntime =
  | 'pymodbus-simulator'
  | 'snap7-simulator'
  | 'cpppo-simulator'
  | 'view-me-mock'
  | 'iec104-simulator'
  | 'opc-ua-mock';

function pickRuntime(track: GenerateCourseInput['track']): LabRuntime {
  switch (track) {
    case 'design':
    case 'capstone':
      return 'cpppo-simulator';
    case 'maintenance':
      return 'view-me-mock';
    case 'risk-assessment':
      return 'snap7-simulator';
    default:
      return 'pymodbus-simulator';
  }
}

function defaultIecParts(track: GenerateCourseInput['track']): string[] {
  switch (track) {
    case 'foundations':       return ['IEC 62443-1-1', 'IEC 62443-2-1'];
    case 'risk-assessment':   return ['IEC 62443-3-2'];
    case 'design':            return ['IEC 62443-3-3', 'IEC 62443-4-2'];
    case 'maintenance':       return ['IEC 62443-2-3', 'IEC 62443-2-4'];
    case 'capstone':
      return [
        'IEC 62443-1-1', 'IEC 62443-2-1', 'IEC 62443-3-2',
        'IEC 62443-3-3', 'IEC 62443-4-2',
      ];
    case 'ics-pentest':       return ['IEC 62443-3-3'];
    case 'ot-defense':        return ['IEC 62443-3-3', 'IEC 62443-2-4'];
    default:                  return ['IEC 62443-1-1'];
  }
}

function defaultIsaLevels(difficulty: GenerateCourseInput['difficulty']): ('SL1' | 'SL2' | 'SL3' | 'SL4')[] {
  switch (difficulty) {
    case 'intro':         return ['SL1', 'SL2'];
    case 'intermediate':  return ['SL2', 'SL3'];
    case 'advanced':      return ['SL3', 'SL4'];
  }
}

function moduleTitles(topic: string, track: GenerateCourseInput['track']): string[] {
  const t = titleCase(topic);
  if (track === 'capstone') {
    return [
      `Capstone Briefing: ${t}`,
      `Practical Phase: ${t}`,
      'Reporting & Oral Defence',
    ];
  }
  return [
    `Concepts: ${t}`,
    `Architectures & Patterns: ${t}`,
    `Threats & Failure Modes: ${t}`,
    `Practical Application: ${t}`,
    `Hands-on Lab: ${t}`,
  ];
}

function lessonTitles(topic: string, modIdx: number): string[] {
  const t = titleCase(topic);
  // 5 modules × 3 lessons = 15 lessons, but variable per module.
  const presets = [
    [`Why ${t} matters`, `Vocabulary and primitives`, `Reading the ${t} threat model`],
    [`Reference architectures for ${t}`, `Zone & conduit application`, `Anti-patterns to avoid`],
    [`Top 10 ${t} weaknesses`, `Real cases: how attackers got in`, `Detection signals you can build`],
    [`A ${t} engagement walkthrough`, `Reporting findings`, `Tying back to IEC 62443 controls`],
    [`Lab brief and toolkit`, `Run the lab end-to-end`, `Submission checklist`],
  ];
  return presets[modIdx] ?? [`Topic ${modIdx}.A`, `Topic ${modIdx}.B`, `Topic ${modIdx}.C`];
}

// ──────────────────────────────────────────────────────────────────────
// Lesson / quiz / lab body rendering — all template based.
// ──────────────────────────────────────────────────────────────────────

function renderLessonMdx(args: {
  topic: string;
  module: string;
  lessonTitle: string;
  lessonId: string;
  durationMin: number;
}): string {
  return `---
title: "${args.lessonTitle}"
duration: "${args.durationMin} min"
---

## Lesson ${args.lessonId} — ${args.lessonTitle}

> Module: **${args.module}**
> Topic: **${args.topic}**

This lesson is a stub generated by the ArmorInnovate mock pipeline. The live
MCP pipeline will replace this body with cited, source-grounded prose. The
schema, file path, and quiz binding are already correct so layout, navigation,
and reading-time computation work today.

### What you should leave with

- A working definition of the lesson title in the context of \`${args.topic}\`.
- One concrete example drawn from a public CISA advisory.
- One question you can ask in the next safety meeting.

### Working definition

(Stub — live pipeline fills this in from the cited sources.)

### Concrete example

(Stub — live pipeline fills this in from a CVE / advisory pulled by the
\`vuln.intel\` MCP server.)

### Question to bring back

(Stub — live pipeline crafts this around the lesson outcomes.)

---

Generated by mock pipeline. Replace with MCP-generated content before publishing.
`;
}

function renderQuizQuestions(args: { topic: string; lessonId: string; count: number }): unknown[] {
  // Generate `count` placeholder MCQs that pass the QuizQuestionSchema.
  const out: unknown[] = [];
  for (let i = 0; i < args.count; i++) {
    out.push({
      question: `(Stub) Lesson ${args.lessonId} placeholder question #${i + 1} on "${args.topic}".`,
      options: [
        'Replace with a plausible distractor (A).',
        'Replace with the correct answer.',
        'Replace with a plausible distractor (C).',
        'Replace with a plausible distractor (D).',
      ],
      answer: 1,
      explanation: `Stub explanation. The live pipeline will derive this from the cited sources for "${args.topic}".`,
    });
  }
  return out;
}

// ──────────────────────────────────────────────────────────────────────
// Public entry — the async generator the CLI / SSE endpoint consumes.
// ──────────────────────────────────────────────────────────────────────

export async function* runMockPipeline(
  input: GenerateCourseInput,
): AsyncGenerator<PipelineEvent, GenerateCourseOutput, void> {
  const t0 = Date.now();
  yield { type: 'pipeline.start', input };

  const slug = input.slug ?? deriveSlug(input.topic);
  const lessonCount = input.lessonCount ?? PIPELINE_DEFAULTS.lessonCount;
  const quizCount = input.quizCount ?? PIPELINE_DEFAULTS.quizCount;

  // Mock "research" steps so the UI has progress to draw.
  yield { type: 'step.start', step: 'docs.search' };
  await tick(120);
  const sources = [
    { url: 'https://webstore.iec.ch/publication/7029', title: 'IEC 62443-1-1' },
    { url: 'https://www.cisa.gov/ics/recommended-practices', title: 'CISA ICS Recommended Practices' },
  ];
  for (const s of sources) yield { type: 'source.found', url: s.url, title: s.title };
  yield { type: 'step.done', step: 'docs.search', durationMs: 120 };

  yield { type: 'step.start', step: 'docs.fetch' };
  await tick(180);
  yield { type: 'step.done', step: 'docs.fetch', durationMs: 180 };

  yield { type: 'step.start', step: 'vuln.intel' };
  await tick(150);
  yield { type: 'step.done', step: 'vuln.intel', durationMs: 150 };

  // ── Lessons ─────────────────────────────────────────────────────
  yield { type: 'step.start', step: 'lessons' };
  const titlesPerModule: string[][] = [];
  const moduleNames = moduleTitles(input.topic, input.track);

  // Distribute lessonCount across modules. We always emit at least 1 per module.
  const perModule = Math.max(1, Math.floor(lessonCount / Math.max(1, moduleNames.length)));
  let lessonIndex = 0;
  const lessons: GeneratedLesson[] = [];
  for (let m = 0; m < moduleNames.length; m++) {
    const titles = lessonTitles(input.topic, m).slice(0, perModule);
    titlesPerModule.push(titles);
    for (let l = 0; l < titles.length; l++) {
      const id = `${m}.${l + 1}`;
      const lesson: GeneratedLesson = {
        id,
        title: titles[l],
        durationMin: 35,
        mdx: renderLessonMdx({
          topic: input.topic,
          module: moduleNames[m],
          lessonTitle: titles[l],
          lessonId: id,
          durationMin: 35,
        }),
        sources: sources.map((s) => s.url),
      };
      lessons.push(lesson);
      yield {
        type: 'lesson.draft',
        index: lessonIndex++,
        title: lesson.title,
        tokens: 420,
      };
      await tick(40);
    }
  }
  yield { type: 'step.done', step: 'lessons', durationMs: lessons.length * 40 };

  // ── Quiz ────────────────────────────────────────────────────────
  yield { type: 'step.start', step: 'quiz' };
  await tick(160);
  // One quiz YAML per lesson — keeps the schema simple. We pick the first
  // lesson as the canonical quiz id; the writer fans out per-lesson quiz
  // YAML files using `quiz.yaml` template below.
  const quiz: GeneratedQuiz = {
    id: lessons[0]?.id ?? '0.1',
    yaml: renderQuizYaml(
      renderQuizQuestions({
        topic: input.topic,
        lessonId: lessons[0]?.id ?? '0.1',
        count: Math.max(3, Math.min(10, quizCount)),
      }),
    ),
  };
  yield { type: 'quiz.draft', questions: quizCount, tokens: 380 };
  yield { type: 'step.done', step: 'quiz', durationMs: 160 };

  // ── Lab ─────────────────────────────────────────────────────────
  yield { type: 'step.start', step: 'lab' };
  await tick(140);
  const runtime = pickRuntime(input.track);
  const labSlug = `${slug}-lab`.slice(0, 80);
  const lab: GeneratedLab = {
    id: labSlug,
    yaml: renderLabYaml({
      slug: labSlug,
      tag: 'LAB-99',
      title: `Hands-on lab: ${titleCase(input.topic)}`,
      shortLabel: titleCase(input.topic).slice(0, 36),
      runtime,
      protocol: defaultProtocol(runtime),
      port: defaultPort(runtime),
      unit: 'tcp',
      difficulty: input.difficulty,
      status: 'queue',
      durationMin: 90,
      track: labTrack(input.track),
      isaLevels: defaultIsaLevels(input.difficulty),
      objectives: [
        `Run the ${titleCase(input.topic)} lab end-to-end on the simulator.`,
        'Capture protocol traffic and identify the attack primitive.',
        'Map findings back to IEC 62443 control requirements.',
      ],
      toolkit: ['wireshark', 'pymodbus-cli', 'snap7-cli', 'opcua-cli'],
      scenario: `Stub scenario for "${input.topic}". The live pipeline replaces this with a real engagement brief grounded in a recent advisory.`,
      successCriteria: [
        'Submit a pcap covering the captured session.',
        'Submit a 200-word brief mapping the finding to a 62443-3-3 SR.',
      ],
      relatedAdvisories: [],
    }),
    dockerfile: dockerfileFor(runtime),
    entrypoint: entrypointFor(runtime),
  };
  yield { type: 'lab.draft', runtime, tokens: 240 };
  yield { type: 'step.done', step: 'lab', durationMs: 140 };

  // ── Course YAML ─────────────────────────────────────────────────
  const courseYaml = renderCourseYaml({
    id: slug,
    title: `${titleCase(input.topic)} — ${trackLabel(input.track)}`,
    shortTitle: titleCase(input.topic).slice(0, 36),
    subtitle: `Auto-generated course on ${titleCase(input.topic)} for the ${trackLabel(input.track)} track.`,
    tagline: `Stub course on ${titleCase(input.topic)}.`,
    summary: `An auto-generated ArmorInnovate course on ${titleCase(input.topic)} for the ${trackLabel(input.track)} track. Replace this body with the live MCP-generated content before publishing.`,
    description: `This course is a deterministic stub produced by the mock pipeline. It is schema-valid and ready to render, but the lesson and quiz bodies should be regenerated by the live MCP pipeline before learners are routed to it.`,
    track: input.track,
    difficulty: input.difficulty,
    status: 'draft',
    iecParts: defaultIecParts(input.track),
    isaLevels: input.isaLevels && input.isaLevels.length > 0 ? input.isaLevels : defaultIsaLevels(input.difficulty),
    hours: Math.max(8, lessons.length * 0.6),
    labHours: 6,
    passingScore: 75,
    tags: ['armor', input.track, slug],
    outcomes: [
      `Explain the core threat model for ${titleCase(input.topic)}.`,
      `Identify two real CVEs that exploit ${titleCase(input.topic)} primitives.`,
      `Map ${titleCase(input.topic)} controls to IEC 62443 requirements.`,
    ],
    prereqs: [],
    sources: sources.map((s) => ({ url: s.url, label: s.title })),
    seoTitle: clamp(`${titleCase(input.topic)} — ArmorInnovate Course`, 59),
    seoDescription: clamp(
      `ArmorInnovate course on ${titleCase(input.topic)}: concepts, threats, controls, and a hands-on lab on the ${runtime}.`,
      170,
    ),
    modules: moduleNames.map((title, i) => ({
      id: String(i),
      title,
      shortLabel: title.split(':')[0].trim().slice(0, 26),
      lessons: titlesPerModule[i].map((lt, j) => ({
        id: `${i}.${j + 1}`,
        title: lt,
        durationMin: 35,
        vmRef: 'mock pipeline',
        // Bind the canonical quiz to lesson 0.1 only; the writer emits a
        // 0.1.yaml quiz file. Other lessons quiz-files come from later runs.
        ...(i === 0 && j === 0 ? { quiz: '0.1.yaml' } : {}),
      })),
    })),
    lab: labFromGenerated(lab, slug),
    generated: {
      by: 'mock',
      at: new Date().toISOString(),
      pipelineVersion: '0.1.0',
    },
  });

  // ── Validate (caller decides what to do) ────────────────────────
  yield { type: 'step.start', step: 'validate' };
  await tick(60);
  yield { type: 'validation', ok: true, messages: [] };
  yield { type: 'step.done', step: 'validate', durationMs: 60 };

  const out: GenerateCourseOutput = {
    slug,
    courseYaml,
    lessons,
    quiz,
    lab,
    diagnostics: {
      warnings: [],
      tokenUsage: 0,
      latencyMs: Date.now() - t0,
      sources,
    },
  };

  yield { type: 'pipeline.done', output: out };
  return out;
}

// ──────────────────────────────────────────────────────────────────────
// Tiny helpers
// ──────────────────────────────────────────────────────────────────────

function tick(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function clamp(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}

function trackLabel(t: GenerateCourseInput['track']): string {
  switch (t) {
    case 'foundations':       return 'Fundamentals Specialist';
    case 'risk-assessment':   return 'Risk Assessment Specialist';
    case 'design':            return 'Design Specialist';
    case 'maintenance':       return 'Maintenance Specialist';
    case 'capstone':          return 'Cybersecurity Expert Capstone';
    case 'ics-pentest':       return 'ICS Pentest';
    case 'ot-defense':        return 'OT Defense';
    default:                  return 'Specialist Track';
  }
}

function labTrack(t: GenerateCourseInput['track']): 'ics-pentest' | 'ot-defense' | 'capstone' {
  if (t === 'capstone') return 'capstone';
  if (t === 'ot-defense' || t === 'maintenance' || t === 'design') return 'ot-defense';
  return 'ics-pentest';
}

function defaultProtocol(runtime: string): string {
  switch (runtime) {
    case 'snap7-simulator':   return 'S7comm';
    case 'cpppo-simulator':   return 'EtherNet/IP (CIP)';
    case 'view-me-mock':      return 'HMI / RDP';
    case 'iec104-simulator':  return 'IEC 60870-5-104';
    case 'opc-ua-mock':       return 'OPC UA';
    default:                  return 'Modbus/TCP';
  }
}

function defaultPort(runtime: string): string {
  switch (runtime) {
    case 'snap7-simulator':   return '102';
    case 'cpppo-simulator':   return '44818';
    case 'view-me-mock':      return '443';
    case 'iec104-simulator':  return '2404';
    case 'opc-ua-mock':       return '4840';
    default:                  return '502';
  }
}

function dockerfileFor(runtime: string): string {
  return `# Dockerfile for ArmorInnovate lab runtime: ${runtime}
FROM python:3.12-slim

ENV LAB_RUNTIME=${runtime}
WORKDIR /lab

RUN pip install --no-cache-dir pymodbus python-snap7 cpppo opcua

COPY entrypoint.sh /lab/entrypoint.sh
RUN chmod +x /lab/entrypoint.sh

EXPOSE 502 102 44818 4840 2404 443
ENTRYPOINT ["/lab/entrypoint.sh"]
`;
}

function entrypointFor(runtime: string): string {
  return `#!/bin/sh
set -eu
echo "[armor-lab] starting runtime ${runtime}"
case "$LAB_RUNTIME" in
  pymodbus-simulator) python -m pymodbus.server --host 0.0.0.0 --port 502 ;;
  snap7-simulator)    python -m snap7.server   --port 102 ;;
  cpppo-simulator)    python -m cpppo.server.enip --print --address 0.0.0.0:44818 ;;
  *)                  echo "no entrypoint for $LAB_RUNTIME"; sleep infinity ;;
esac
`;
}

function labFromGenerated(g: GeneratedLab, slug: string) {
  // Embed a schema-shaped lab object inside the course.yaml so /knowledge
  // detail pages can render the bundled lab without a second file read.
  return {
    slug: g.id,
    tag: 'LAB-99',
    title: `Hands-on lab for ${slug}`,
    shortLabel: slug.slice(0, 36),
    runtime: pickRuntime('foundations'),
    protocol: 'Modbus/TCP',
    port: '502',
    unit: 'tcp' as const,
    difficulty: 'intro' as const,
    status: 'queue' as const,
    durationMin: 90,
    track: 'ics-pentest' as const,
    isaLevels: ['SL1', 'SL2'] as ('SL1' | 'SL2' | 'SL3' | 'SL4')[],
    objectives: ['Run the bundled lab.', 'Capture traffic.', 'Submit findings.'],
    toolkit: ['wireshark', 'pymodbus-cli'],
    scenario: 'Stub scenario produced by the mock pipeline. Replace before publishing.',
    successCriteria: ['Submit a pcap.', 'Submit a 200-word brief.'],
    relatedAdvisories: [],
  };
}
